"""Add User

Revision ID: 850620665f0b
Revises: e6d861f0bf8c
Create Date: 2026-02-20 14:01:50.582349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850620665f0b'
down_revision = 'e6d861f0bf8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
