"""Add Comment (EDITED)

Revision ID: e6d861f0bf8c
Revises: c240beb054af
Create Date: 2026-01-23 15:04:46.485146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d861f0bf8c'
down_revision = 'c240beb054af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=250), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
